spring.application.name=demo

spring.datasource.url=jdbc:postgresql://YOUR_RDS_ENDPOINT:5432/YOUR_DB_NAME
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable the web console so we can see our database in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#aws keys and region
cloud.aws.credentials.access-key=YOUR_ACCESS_KEY
cloud.aws.credentials.secret-key=YOUR_SECRET_KEY
cloud.aws.region.static=YOUR_REGION

app.s3.bucket-name=YOUR_BUCKET_NAME